trigger:
  - master
pool:
  name: default
jobs:
- job: "job 1"
  displayName: buid game of life
  steps: 
    - task: Maven@3
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'path'
        jdkVersionOption: '1.8'
        jdkDirectory:  '/usr/lib/jvm/java-8-openjdk-amd64/'
        mavenVersionOption: 'path'
        mavenDirectory: '/usr/share/maven'
    - task: CopyFiles@2
      inputs:
        Contents: "**/target/gameoflife.war" 
        TargetFolder: $(build.artifactstagingdirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: gameoflifeartifact
       