trigger:
  - master

jobs:
- job: build_with_java_8
  displayName: 'Build with Java 8'
  pool:
    name: default 
  variables:
    JAVA_HOME: '/usr/lib/jvm/java-8-openjdk-amd64'
    PATH: '$(JAVA_HOME)/bin:$(PATH)'
  steps:
    - task: Maven@3
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
 